[project]
name = "kgraphing-ontology-datamodelling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gravis",
    "kgraphing",
    "maplib>=0.20.26",
    "polars>=1.44.1",
]

[tool.uv.sources]
kgraphing = { git = "https://github.com/ThomasKimber/kgraph", branch = "main" }
gravis = { url = "https://github.com/raufs/gravis/archive/refs/tags/v0.1.1.tar.gz" }
